spring.data.mongodb.uri=mongodb+srv://ashutoshsharma_db_user:Tozc2rVxlYperrOc@cluster0.pla4af3.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journalDb
spring.data.mongodb.auto-index-creation=true